export const heroCrawlLines: string[] = [
  'The year is 2044. Fifteen years ago, the world shattered.',
  'An egomaniacal empire broke the world with one button.',
  'From the fallout rose a single order: The Regime.',
  'Fear dressed as justice.',
  'They built the Maze,',
  'A ruthless, shifting labyrinth of concrete and misery.',
  'The condemned are thrown inside with one impossible chance:',
  'Survive and Escape. Be pardoned for your crimes.',
  'OR DIE',
  'Every room a test, every shadow has teeth.',
  'Others may prove an ally, or they may betray you.',
  'Wardens rule the deepest sectors blocking the path forward.',
  'The Regime calls it justice. The masses call it entertainment.',
  'The Maze is now your home. It expects you to die.',
]

export const fullStoryParagraphs: string[] = [
  'The year 2044. Fifteen years ago, the world ended. Not with silence, but with sirens, fire, and cities erased in a single flash.',
  'One egomaniacal empire broke the world\'s spine with the press of a button. Retaliation finished the job. Nukes rained. Nations burned. Governments collapsed. Civilization drowned in ash, radiation, and panic.',
  'From the ruins rose a new order: ruthless, absolute, and unforgiving. The Regime promised survival and delivered fear.',
  'Under The Regime, justice became theater. Guilt became whatever they said it was. Rebels, looters, deserters, dissenters, and war criminals were all fed into the same machine.',
  'That machine is the Death Maze. Buried beneath the bones of the old world, it was built as punishment, spectacle, and warning.',
  'No one enters the Maze to live. They enter to be judged. They enter to die.',
  'You are one of the condemned, thrown into the dark with a promise whispered through prison camps and execution yards: survive the Maze, escape its depths, and earn a pardon for your crimes against humanity.',
  'Maybe it is true. Maybe it is just one more lie.',
  'Inside, every step is a gamble. Every room is a test. Every sound could be a clue, or the last thing you hear.',
  'You will not be alone. Others may become allies. They may help you fight, search, and survive. Or they may sabotage you, betray you, and leave your body cooling in the dark.',
  'In the Maze, trust is a risk and friendly fire is never an accident for long.',
  'The labyrinth is not empty. The halls crawl with things born from radiation, madness, failed experiments, and years of unchecked horror.',
  'Over them rule the Wardens, monstrous bosses who control each domain and guard the keys to deeper sectors.',
  'To move forward, you must face them. To face them, you must survive everything beneath them. The deeper you go, the less human the Maze becomes.',
  'The Regime calls this justice. The masses call it entertainment. The Wardens call it home.',
  'But rumors persist: someone once reached the final gate. The Maze may have an end. Beneath all the blood and ruin, there may still be a way out.',
  'A way to live. A way to be free. A way to become what no one expects a condemned soul to become: a hero.',
  'The Maze does not care who you were before you entered. It only cares how long you last. Choose your alliances carefully. Watch every doorway. Count every bullet. Keep moving.',
  'Because in Death Maze 2044, you are not expected to win. You are expected to die.',
]
